services:
  neo4j:
    image: neo4j:5.12.0-community
    restart: unless-stopped
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
    networks:
      - ebl-net

networks:
  ebl-net:
    name: ebl
    external: true